spring:
  application:
    name: x-ai-agent
  profiles:
    active: local
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        #dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

    mcp:
      client:
        streamable-http:
          server-connections:
            amap-maps:
              base-url: https://dashscope.aliyuncs.com/api/v1/mcps/amap-maps/mcp
              headers:
                Authorization: Bearer ${spring.ai.dashscope.api-key}
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

server:
  port: 8123
  servlet:
      context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.x.xaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

#logging:
#  level:
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
#
#logging:
#  level:
#    org.springframework.ai.vectorstore.pgvector: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG
